export const GET_EMPLOYEES_LIST = "GET_EMPLOYEES_LIST";
export const LOGIN_EMPLOYEE = "LOGIN_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const GET_SERVED_ORDERS = "GET_SERVED_ORDERS";
export const GET_ORDERS_TO_BE_SERVED = "GET_ORDERS_TO_BE_SERVED";
export const SERVE_ORDER = "SERVE_ORDER";
export const PAY_ORDER = "PAY_ORDER";
export const GET_MENU = "GET_MENU";
export const GET_ORDERS_TO_BE_PREPARED = "GET_ORDERS_TO_BE_PREPARED";
export const GET_ON_PREPARATION_ORDERS = "GET_ON_PREPARATION_ORDERS";
export const PREPARE_ORDER = "PREPARE_ORDER";
export const ORDER_PREPARED = "ORDER_PREPARED";
export const PAY_DELIVERY_ORDER = "PAY_DELIVERY_ORDER";
export const DELIVER_ORDER = "DELIVER_ORDER";
export const GET_ORDERS_TO_BE_DELIVERD = "GET_ORDERS_TO_BE_DELIVERD";
export const GET_ON_DELIVERY_ORDERS = "GET_ON_DELIVERY_ORDERS";

export const GET_ONLINE_ORDERS = "GET_ONLINE_ORDERS";
export const VALIDE_ORDER = "VALIDE_ORDER";

export const ADD_PLAT = "ADD_PLAT";
export const EDIT_PLAT = "EDIT_PLAT";
export const DELETE_PLAT = "DELETE_PLAT";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const GET_TABLE_LIST = "GET_TABLE_LIST";
export const GET_OCCUPIED_TABLE_LIST = "GET_OCCUPIED_TABLE_LIST";
export const GET_NON_OCCUPIED_TABLE_LIST = "GET_NON_OCCUPIED_TABLE_LIST";
export const ADD_TABLE = "ADD_TABLE";
export const EDIT_TABLE = "EDIT_TABLE";
export const DELETE_TABLE = "DELETE_TABLE";
